// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWphY5YUakDQqzd3Ww348qveVl3QjOh5Q',
    appId: '1:247472872760:web:82b8b557a743cfa674b5cd',
    messagingSenderId: '247472872760',
    projectId: 'buzzbuddy-869c8',
    authDomain: 'buzzbuddy-869c8.firebaseapp.com',
    storageBucket: 'buzzbuddy-869c8.appspot.com',
    measurementId: 'G-TD4YE66FJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE2KqROwY0r9A8WpVaZlkWGtrPo3Au-Vw',
    appId: '1:247472872760:android:bcd79055b80ea78c74b5cd',
    messagingSenderId: '247472872760',
    projectId: 'buzzbuddy-869c8',
    storageBucket: 'buzzbuddy-869c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe-Is_7_4ZlROKmn-um2WtHSup5Knun5I',
    appId: '1:247472872760:ios:78b277e6c364807774b5cd',
    messagingSenderId: '247472872760',
    projectId: 'buzzbuddy-869c8',
    storageBucket: 'buzzbuddy-869c8.appspot.com',
    iosBundleId: 'com.example.buzzBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe-Is_7_4ZlROKmn-um2WtHSup5Knun5I',
    appId: '1:247472872760:ios:78b277e6c364807774b5cd',
    messagingSenderId: '247472872760',
    projectId: 'buzzbuddy-869c8',
    storageBucket: 'buzzbuddy-869c8.appspot.com',
    iosBundleId: 'com.example.buzzBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWphY5YUakDQqzd3Ww348qveVl3QjOh5Q',
    appId: '1:247472872760:web:3bcd3f3abecfb52c74b5cd',
    messagingSenderId: '247472872760',
    projectId: 'buzzbuddy-869c8',
    authDomain: 'buzzbuddy-869c8.firebaseapp.com',
    storageBucket: 'buzzbuddy-869c8.appspot.com',
    measurementId: 'G-KWDTRGKBGJ',
  );
}
